name: App CI
on: push
jobs:
  run-test-unit-and-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test
